### PR TITLE
Add privatelink for azurewebsites

### PR DESCRIPTION
**Pull request by manuelcoppotelli**
### List of changes

* private dns zone
* virtual network link

### Motivation and context

So that appservice and functionapp can have private endpoint

### Type of changes

- [x] Add new resources
- [ ] Update configuration to existing resources
- [ ] Remove existing resources

### Env to apply

- [] DEV
- [x] UAT
- [x] PROD

### Does this introduce a change to production resources with possible user impact?

- [ ] Yes, users may be impacted applying this change
- [x] No

### Does this introduce an unwanted change on infrastructure? Check terraform plan execution result

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by pasqualedevita — COMMENTED** [review]
Why you need private endpoints for azure functions or app service?
Not a problem to enable it but others functions/app service does not use it

Anyway I suggest to add private link also for vnet_beta and vnet_prod01
https://github.com/pagopa/io-infra/pull/321/files

**Comment by manuelcoppotelli** [comment]
@pasqualedevita It would be helpful to reach the function endpoints via VPN, so that we can them directly. Whitelisting the IPs as `allowed_ips` is unpractical.
At the same time the functions should remain "internal" in order to be called by the APIM.

**Comment by pasqualedevita** [comment]
> @pasqualedevita It would be helpful to reach the function endpoints via VPN, so that we can them directly. Whitelisting the IPs as `allowed_ips` is unpractical. At the same time the functions should remain "internal" in order to be called by the APIM.

LGTM we have only a drawback: using private endpoint we have to delete `allowed_subnets` on function app and add a network security group

**Comment by manuelcoppotelli** [comment]
> LGTM we have only a drawback: using private endpoint we have to delete `allowed_subnets` on function app and add a network security group

Yes. Since each of our functionapp is in a dedicated subnet, adding a NSG should not be a problem.
Do you see any potential blocks?

**Review by pasqualedevita — APPROVED** [review]

**Comment by pasqualedevita** [comment]
> > LGTM we have only a drawback: using private endpoint we have to delete `allowed_subnets` on function app and add a network security group
> 
> Yes. Since each of our functionapp is in a dedicated subnet, adding a NSG should not be a problem. Do you see any potential blocks?

it's ok we can merge and deploy, we can introduce NSG after

**Pull request merged**
