### PR TITLE
[EC-268] Add scheduled autoscale rules for messages function apps

### PR DESCRIPTION
**Pull request by Krusty93**
### List of changes

Add two scaling rules to the existing one:
- set minimum instances to 4 during the time range 19:50-21:00
- set minimum instances to 2 during the time range 01:00-05:00

### Motivation and context

Improving scaling automation for sudden spikes. So we scale in advance

### Type of changes

- [ ] Add new resources
- [X] Update configuration to existing resources
- [ ] Remove existing resources

### Env to apply

- [ ] DEV
- [ ] UAT
- [X] PROD

### Does this introduce a change to production resources with possible user impact?

- [X] Yes, users may be impacted applying this change
- [ ] No

### Does this introduce an unwanted change on infrastructure? Check terraform plan execution result

- [ ] Yes
- [X] No

### Other information

---

### How to apply

After PR is approved
1. run deploy pipeline from Azure DevOps [io-platform-iac-projects](https://dev.azure.com/pagopaspa/io-platform-iac-projects/_build?view=folders)
2. select PR branch
3. wait for approval

### CODE REVIEW

**Comment by gunzip** [comment]
this looks complicated to maintain, what's the downside in keeping the same settings all day (and night) long? higher costs? like what?

**Comment by Krusty93** [comment]
> this looks complicated to maintain, what's the downside in keeping the same settings all day (and night) long? higher costs? like what?

Waste of money and resources basically. For example, we are using 4 instances 24/7, but during the night 1 would be more than sufficient. By applying the same pattern to all services and functions we can save lot of money.

Also, consider keeping 4 instances running 24/7 might not be that expensive, but when the IT Wallet will be released and we might need let's say 20 instances, savings would be consistent.

**Comment by gunzip** [comment]
If it's the same pattern, can it be abstracted away into its own module someway?

**Comment by Krusty93** [comment]
> If the pattern repeats, could we abstract it into a dedicated module somehow? Do we have an estimate of the potential savings this abstraction might offer?

We have [this WIP example](https://github.com/pagopa/io-infra/blob/2569a193bf7c70b7a75e2c0899b2a7467d9aec87/src/domains/ioweb-app/06_function_ioweb_profile.tf#L215) but we are losing the flexibility to change threshold for each rule separately

**Pull request merged**
