### PR TITLE
[#IC-194] Add database for `subscription-migrations`

### PR DESCRIPTION
**Pull request by balanza**
### List of changes

* add a `postgres` instance dedicated to `subscription-migrations`

### Motivation and context

As persistence is needed by `subscription-migrations`, this PR declares a dedicated database instance for such application. 
The served workflow won't be intensive in term of incoming traffic and exchanged data; furthermore, we plan to dismantle the application in a reasonable span of time (~6mo), as it only serves the purpose of moving our users from `developers.io.italia.it` to `io.selfcare.pagopa.it`. 

Given that, we choose `postgres` as an opportunity to introduce it in `IO` and evaluate if it could be a viable option for other scenarios. 

### Type of changes

- [x] Add new resources
- [ ] Update configuration to existing resources
- [ ] Remove existing resources

### Env to apply

- [ ] DEV
- [ ] UAT
- [x] PROD

### Does this introduce a change to production resources with possible user impact?

- [ ] Yes, users may be impacted applying this change
- [x] No

### Does this introduce an unwanted change on infrastructure? Check terraform plan execution result

- [ ] Yes
- [ ] No

### Other information

---

### CODE REVIEW

**Comment by balanza** [comment]
@pasqualedevita I'm facing this error but I cannot understand why
> Error: expected version to be one of [9.5 9.6 11 10 10.0], got 13

As for Azure docs, Postgres [Flexible Server](https://docs.microsoft.com/en-us/azure/postgresql/flexible-server/concepts-supported-versions) should support v13. Conversely, [Single Server](https://docs.microsoft.com/en-us/azure/postgresql/concepts-supported-versions) only supports up to v11.

We defined `sku_name = GP_Gen5_2`, as I assumed it stands for flexible server solution, but now I think that was a wrong assumption by us.

**Comment by pasqualedevita** [comment]
> @pasqualedevita I'm facing this error but I cannot understand why
> 
> > Error: expected version to be one of [9.5 9.6 11 10 10.0], got 13
> 
> As for Azure docs, Postgres [Flexible Server](https://docs.microsoft.com/en-us/azure/postgresql/flexible-server/concepts-supported-versions) should support v13. Conversely, [Single Server](https://docs.microsoft.com/en-us/azure/postgresql/concepts-supported-versions) only supports up to v11.
> 
> We defined `sku_name = GP_Gen5_2`, as I assumed it stands for flexible server solution, but now I think that was a wrong assumption by us.
> 
> UPDATE: I now realize we have different terraform modules for single and flexible postgres server. I need to make up my mind whether we can live with a single server instance, otherwise I'll have to write a custom flexible server terraform provider that mimics what we did for [single server](https://github.com/pagopa/azurerm/tree/main/postgresql_server).

yes postgresql flexible server is a different terraform resource

**Comment by balanza** [comment]
> > @pasqualedevita I'm facing this error but I cannot understand why
> > > Error: expected version to be one of [9.5 9.6 11 10 10.0], got 13
> > 
> > 
> > As for Azure docs, Postgres [Flexible Server](https://docs.microsoft.com/en-us/azure/postgresql/flexible-server/concepts-supported-versions) should support v13. Conversely, [Single Server](https://docs.microsoft.com/en-us/azure/postgresql/concepts-supported-versions) only supports up to v11.
> > We defined `sku_name = GP_Gen5_2`, as I assumed it stands for flexible server solution, but now I think that was a wrong assumption by us.
> > UPDATE: I now realize we have different terraform modules for single and flexible postgres server. I need to make up my mind whether we can live with a single server instance, otherwise I'll have to write a custom flexible server terraform provider that mimics what we did for [single server](https://github.com/pagopa/azurerm/tree/main/postgresql_server).
> 
> yes postgresql flexible server is a different terraform resource

So in the end, I decided to use Single Server as we won't need to scale up. I changed db version in https://github.com/pagopa/io-infra/pull/82/commits/d11abd57a50e53efb55c217e2ed09dbe2f56f439

**Review by uolter — DISMISSED** [review]

**Review by pasqualedevita — CHANGES_REQUESTED** [review]
terraform init fails, probably a wrong source reference

**Review by uolter — DISMISSED** [review]

**Review by pasqualedevita — APPROVED** [review]

**Pull request merged**
